#! /bin/bash
## Modify HTML styles generated by vs codium.

## Figure out what directory this script is in
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
checkout_dir=${script_dir}/..

## VS codium puts the HTML in the target dir
doc_src_dir=${checkout_dir}/src-doc
doc_dir=${checkout_dir}/Documentation
source_file=${doc_dir}/SparkleInstall.html
dest_file=${doc_src_dir}/SparkleInstall.html

cd ${checkout_dir}
awk -f ${doc_src_dir}/StyleHtml.awk ${source_file} > ${dest_file} \
    && ( rm ${source_file} )
