Class {
	#name : 'SpkAccordianLayoutCell',
	#superclass : 'SpkLayoutCell',
	#instVars : [
		'optimalSize',
		'priority'
	],
	#category : 'Sparkle-Spextensions-MorphicLayout'
}

{ #category : 'accessing' }
SpkAccordianLayoutCell >> optimalSize [

	^ optimalSize
]

{ #category : 'accessing' }
SpkAccordianLayoutCell >> optimalSize: anObject [

	optimalSize := anObject
]

{ #category : 'accessing' }
SpkAccordianLayoutCell >> priority [

	^ priority
]

{ #category : 'accessing' }
SpkAccordianLayoutCell >> priority: anObject [

	priority := anObject
]
