Class {
	#name : 'SpkAccordianLayoutCell',
	#superclass : 'SpkLayoutCell',
	#instVars : [
		'allocationFactor'
	],
	#category : 'Sparkle-Spextensions-MorphicLayout',
	#package : 'Sparkle-Spextensions',
	#tag : 'MorphicLayout'
}

{ #category : 'accessing' }
SpkAccordianLayoutCell >> allocationFactor [

	^ allocationFactor
]

{ #category : 'accessing' }
SpkAccordianLayoutCell >> allocationFactor: anObject [

	allocationFactor := anObject
]
