Extension { #name : 'RsrForwarder' }

{ #category : '*Sparkle-Scaffolding-Pharo' }
RsrForwarder >> allInspectorNodes [

	^ #()
]

{ #category : '*Sparkle-Scaffolding-Pharo' }
RsrForwarder >> basicSize [
    ^ 0
]

{ #category : '*Sparkle-Scaffolding-Pharo' }
RsrForwarder >> isKindOf: ignored [

    ^ false

]

{ #category : '*Sparkle-Scaffolding-Pharo' }
RsrForwarder >> stDisplayString [

	^ 'a RsrForwarder'
]
