Class {
	#name : 'SpkInspectorRawViewService',
	#superclass : 'SpkInspectorFieldListViewService',
	#category : 'Sparkle-Services-Common-Services',
	#package : 'Sparkle-Services-Common',
	#tag : 'Services'
}

{ #category : 'accessing' }
SpkInspectorRawViewService class >> templateClassName [

	^ #SpkInspectorRawViewService
]

{ #category : 'accessing' }
SpkInspectorRawViewService >> numberOfColumns [

	^ 2
]
