Class {
	#name : 'SpkInspectorSetViewService',
	#superclass : 'SpkInspectorFieldListViewService',
	#category : 'Sparkle-Services-Common-Services',
	#package : 'Sparkle-Services-Common',
	#tag : 'Services'
}

{ #category : 'accessing' }
SpkInspectorSetViewService class >> templateClassName [

	^ #SpkInspectorSetViewService
]

{ #category : 'accessing' }
SpkInspectorSetViewService >> numberOfColumns [

	^ 1
]
