"
Execution has occurred. Values in inspectors may have changed.
"
Class {
	#name : 'SpkExecutionAnnouncement',
	#superclass : 'Announcement',
	#instVars : [
		'updatedServices'
	],
	#category : 'Sparkle-Tools-Common'
}

{ #category : 'accessing' }
SpkExecutionAnnouncement >> updatedServices [
	^updatedServices
]

{ #category : 'accessing' }
SpkExecutionAnnouncement >> updatedServices: object [
	updatedServices := object
]
